### ISSUE TITLE
Mixins shouldn't generate nominal typing

### ISSUE THREAD

**Issue by kainino0x** [darionco/bikeshed-to-ts#5]
This code from the WebGPU spec:
```webidl
interface mixin NavigatorGPU {
    [SameObject] readonly attribute GPU gpu;
};
Navigator includes NavigatorGPU;
```
generates:
```ts
  interface Navigator {
    /**
     * Nominal type branding.
     * https://github.com/microsoft/TypeScript/pull/33038
     * @internal
     */
    readonly __brand: "Navigator";
    readonly gpu: GPU;
  }
```
but shouldn't make this externally-defined interface suddenly become nominally typed:
```ts
  interface Navigator {
    readonly gpu: GPU;
  }
```

**Comment by darionco** [comment]
This one is weird, it produces different code for me, not sure why yours is doing that. The version I am working with produces:
```ts
interface NavigatorGPU {
    readonly gpu: GPU;
}
interface Navigator extends NavigatorGPU {
}
```

I am going to close this one for now, feel free to reopen it if the issue reappears in the new version (will release it later today)

**Comment by kainino0x** [comment]
I may be using an older version of the spec, I didn't think to check that. Thanks!

**Comment by kainino0x** [comment]
Yup, that was it.
