### ISSUE TITLE
IDL `interface` should generate both TS `interface` and `var`

### ISSUE THREAD

**Issue by kainino0x** [darionco/bikeshed-to-ts#7]
Here's an example from TypeScript's `lib.dom.d.ts`:
https://github.com/microsoft/TypeScript/blob/16031bc429305e5daabf263f208678a6729a161e/lib/lib.dom.d.ts#L6490-L6525
```ts
interface HTMLCanvasElement extends HTMLElement {
    // ...
}
declare var HTMLCanvasElement: {
    prototype: HTMLCanvasElement;
    new(): HTMLCanvasElement;
};
```

**Comment by kainino0x** [comment]
Neither of these suggestions matches `lib.dom.d.ts`, but perhaps:
- `.prototype` should be `readonly` (browser doesn't actually seem to allow overwriting it).
- `new()` should be omitted for non-constructible interfaces.

```ts
declare var GPUBuffer: {
    readonly prototype: GPUBuffer;
};
```

Or as a compromise:
```ts
declare var GPUBuffer: {
    readonly prototype: GPUBuffer;
    new(): never;
};
``

**Comment by kainino0x** [comment]
Ah, another thing. `const` items like:
```webidl
interface GPUBufferUsage {
    const GPUFlagsConstant MAP_READ      = 0x0001;
    // ...
}
```
should be visible on the `var` itself as well (they're like static members). Not sure what the best way to express this is. Maybe just duplicating? (I'd check `lib.dom.d.ts` but don't know of other examples offhand.)
```ts
  var GPUBufferUsage: {
    prototype: GPUBufferUsage;
    readonly MAP_READ: GPUFlagsConstant;
    // ...
  };
  interface GPUBufferUsage {
    readonly MAP_READ: GPUFlagsConstant;
    // ...
  }
```
The browser behavior seems to support this:
```
> GPUBufferUsage
ƒ GPUBufferUsage() { [native code] }
> GPUBufferUsage.__proto__
ƒ () { [native code] }
> GPUBufferUsage.COPY_DST
8

> GPUBufferUsage.prototype
GPUBufferUsage {MAP_READ: 1, MAP_WRITE: 2, COPY_SRC: 4, COPY_DST: 8, INDEX: 16, …}
> GPUBufferUsage.prototype.__proto__
{constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …}
> GPUBufferUsage.prototype.COPY_DST
8
```

**Comment by kainino0x** [comment]
Yet another note: currently constructible things have a `new()` on their interface, but I _think_ it should be on the `var` instead.

**Comment by darionco** [comment]
For this one I followed the format as closely as possible to [lib.webworker.d.ts](https://github.com/microsoft/TypeScript/blob/131875bb849c0a9c56c26d09881453aace0cbfed/lib/lib.webworker.d.ts)
